[versions]
gradleplugin = "7.1.3"
kotlin = "1.6.10"
core-ktx = "1.8.0"
appcompat = "1.5.0"
material = "1.6.1"
constraintlayout = "2.1.4"
gson = "2.9.0"
junit = "4.13.2"
test-junit = "1.1.3"
test-espresso-core = "3.4.0"
hilt = "2.43.2"
hilt-compiler = "1.0.0"
navigation = "2.5.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core.ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compiler" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[bundles]
androidx = ["androidx-core-ktx", "androidx-appcompat", "androidx-constraintlayout","androidx-navigation-fragment", "androidx-navigation-ui"]
test = ["androidx-test-ext-junit", "androidx-test-espresso-core"]
hilt-compiler = ["hilt-android-compiler", "hilt-compiler"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
hilt-gradlePlugin = { id = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }